[package]
name = "fuchsia_ui_composition"
version = "0.1.0"
edition = "2021"

[dependencies]
fidl = { path = "../../third_party/fuchsia-sdk-rust/fidl" }
fuchsia-zircon = { path = "../../third_party/fuchsia-sdk-rust/fuchsia-zircon" }
bitflags = "1.3"
futures = "0.3"

[lib]
path = "src/lib.rs"
